package doctor

import (
	"fmt"
	"strings"
)

// FormatAgentMarkdown renders diagnostics as markdown for coding agents.
func FormatAgentMarkdown(r Report) string {
	var b strings.Builder
	b.WriteString("# IntentProof doctor report\n\n")
	b.WriteString("Generated by `intentproof doctor --agent`. Fix `[fail]` items first.\n\n")
	if r.HasFailures() {
		b.WriteString("**Status:** one or more checks failed.\n\n")
	} else {
		b.WriteString("**Status:** no blocking failures.\n\n")
	}

	b.WriteString("## Checks\n\n")
	for _, c := range r.Checks {
		b.WriteString(fmt.Sprintf("### %s (%s)\n\n", c.Name, c.Status))
		b.WriteString(c.Detail + "\n\n")
		if c.Hint != "" {
			b.WriteString("**Next:** " + c.Hint + "\n\n")
		}
	}

	b.WriteString("## Agent constraints\n\n")
	b.WriteString("- Re-run `intentproof doctor` after each fix until no `[fail]` checks remain.\n")
	b.WriteString("- Use `intentproof init --agent` for project-specific setup steps.\n")
	b.WriteString("- Do not treat this report as proof; signed events come from SDK `wrap()`.\n")
	b.WriteString("- Preset hints recognize demo action aliases (`ledger.entry.write`, `customer.notify`).\n\n")

	b.WriteString("## Verify\n\n")
	b.WriteString("```bash\n")
	b.WriteString("intentproof demo refund\n")
	b.WriteString("intentproof doctor --agent\n")
	b.WriteString("```\n")
	return b.String()
}
