# syntax=docker/dockerfile:1.7

FROM --platform=$BUILDPLATFORM golang:1.25.0-alpine@sha256:f18a072054848d87a8077455f0ac8a25886f2397f88bfdd222d6fafbb5bba440 AS build
WORKDIR /src

ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
ARG COMMIT=unknown
ARG DATE=unknown
ARG SOURCE_DATE_EPOCH=0

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath \
    -ldflags="-s -w -buildid= \
    -X github.com/intentproof/intentproof-tools/pkg/buildinfo.Version=${VERSION} \
    -X github.com/intentproof/intentproof-tools/pkg/buildinfo.Commit=${COMMIT} \
    -X github.com/intentproof/intentproof-tools/pkg/buildinfo.Date=${DATE}" \
    -o /out/intentproof ./cmd/intentproof
RUN mkdir -p /out/home/nonroot/.intentproof/local && \
    chown -R 65532:65532 /out/home/nonroot

FROM scratch
ENV HOME=/home/nonroot
ENV INTENTPROOF_LOCAL_OPEN_BROWSER=0
COPY --from=build /out/intentproof /intentproof
COPY --from=build --chown=65532:65532 /out/home/nonroot /home/nonroot
USER 65532:65532
EXPOSE 9787 9788 9789
VOLUME ["/home/nonroot/.intentproof/local"]
ENTRYPOINT ["/intentproof", "local"]
