package initdetect

import (
	"fmt"
	"strings"
)

// FormatAgentMarkdown renders project detection as agent-oriented markdown.
func FormatAgentMarkdown(p Project) string {
	var b strings.Builder
	b.WriteString("# IntentProof implementation guide\n\n")
	b.WriteString("Generated by `intentproof init --agent`. Follow steps in order.\n\n")
	writeAgentMarkdownBody(&b, p)
	return b.String()
}

// FormatStripeRefundAgentMarkdown adds the Path 3 wedge outline for agents.
func FormatStripeRefundAgentMarkdown(p Project) string {
	var b strings.Builder
	b.WriteString("# IntentProof Stripe Refund Proof (agent guide)\n\n")
	b.WriteString("Generated by `intentproof init --template stripe-refund --agent`. ")
	b.WriteString("Follow steps in order.\n\n")
	writeAgentMarkdownBody(&b, p)
	b.WriteString("\n## Path 3 wedge steps (preview)\n\n")
	b.WriteString("Complete these when reconciliation adapters are available. ")
	b.WriteString("Until then, run `intentproof demo refund` for the reference flow.\n\n")
	steps := []struct {
		desc string
		cmd  string
	}{
		{"Wrap the refund call", "payments.refund.execute"},
		{"Propagate correlation IDs", "use W3C traceparent or run_with_correlation_id"},
		{"Connect Stripe webhook", "stripe listen --forward-to <ingest-url>"},
		{"Verify webhook HMAC", "intentproof sources test <source_id>"},
		{"Activate preset policy", "reference.payments.refund-with-notification.v1"},
		{"Run a Stripe test refund", "(Stripe test mode)"},
		{"Trigger a deliberate divergence", "(see wedge MVP failure modes)"},
		{"Inspect the finding", "intentproof findings show <id>"},
		{"Export a proof bundle", "intentproof bundle export <run_id>"},
	}
	for i, step := range steps {
		b.WriteString(fmt.Sprintf("%d. **%s**", i+1, step.desc))
		if step.cmd != "" {
			if strings.Contains(step.cmd, " ") && !strings.HasPrefix(step.cmd, "payments.") {
				b.WriteString("\n\n   ```bash\n   " + step.cmd + "\n   ```\n")
			} else if strings.HasPrefix(step.cmd, "payments.") {
				b.WriteString(" — action `" + step.cmd + "`\n")
			} else {
				b.WriteString("\n\n   `" + step.cmd + "`\n")
			}
		} else {
			b.WriteByte('\n')
		}
	}
	b.WriteString("\n")
	return b.String()
}

func writeAgentMarkdownBody(b *strings.Builder, p Project) {
	writeAgentProjectSummary(b, p)
	writeAgentDetected(b, p)
	writeAgentNotDetected(b, p)
	writeAgentDoNext(b, p)
	writeAgentConstraints(b, p)
	writeAgentNextCommands(b, p)
}

func writeAgentProjectSummary(b *strings.Builder, p Project) {
	b.WriteString("## Project\n\n")
	b.WriteString("- **Root:** `" + p.Root + "`\n")
	b.WriteString("- **Primary stack:** `" + p.Primary + "`\n\n")
}

func writeAgentDetected(b *strings.Builder, p Project) {
	b.WriteString("## Detected environment\n\n")
	if len(p.Detected) == 0 {
		b.WriteString("- (none)\n\n")
		return
	}
	for _, item := range p.Detected {
		b.WriteString(fmt.Sprintf("- **%s:** %s\n", item.Label, item.Detail))
	}
	b.WriteByte('\n')
}

func writeAgentNotDetected(b *strings.Builder, p Project) {
	if len(p.NotFound) == 0 {
		return
	}
	b.WriteString("## Not detected\n\n")
	for _, line := range p.NotFound {
		b.WriteString("- " + line + "\n")
	}
	b.WriteByte('\n')
}

func writeAgentDoNext(b *strings.Builder, p Project) {
	b.WriteString("## Do next (in order)\n\n")
	for i, line := range p.Recommend {
		desc, cmd, ok := agentCommandFromStep(line)
		if ok {
			b.WriteString(fmt.Sprintf("%d. %s\n\n", i+1, desc))
			b.WriteString("   ```bash\n   " + cmd + "\n   ```\n\n")
			continue
		}
		b.WriteString(fmt.Sprintf("%d. %s\n\n", i+1, line))
	}
}

func writeAgentConstraints(b *strings.Builder, p Project) {
	b.WriteString("## Constraints\n\n")
	b.WriteString("- Use developer-supplied **intent** strings; do not infer intent at capture time.\n")
	b.WriteString("- First wrapped refund action should be `payments.refund.execute` unless the project uses a different verified flow.\n")
	b.WriteString("- **wrap()** signs execution facts; MCP or tool capture supplements but does not replace it.\n")
	b.WriteString("- Do not author policy YAML from scratch; use reference packs (`intentproof reference list`) or dashboard presets.\n")
	b.WriteString("- Proof is post-hoc verification, not a real-time approval gate.\n\n")
	_ = p
}

func writeAgentNextCommands(b *strings.Builder, p Project) {
	b.WriteString("## Verify setup\n\n")
	b.WriteString("```bash\n")
	b.WriteString("intentproof demo refund\n")
	if p.Primary == "node" || hasStripe(p) {
		b.WriteString("intentproof init --template stripe-refund --agent\n")
	}
	b.WriteString("```\n")
}

func agentCommandFromStep(line string) (desc string, cmd string, ok bool) {
	if i := strings.Index(line, ": "); i >= 0 {
		head := strings.TrimSpace(line[:i])
		tail := strings.TrimSpace(line[i+2:])
		if looksShellCommand(tail) {
			return head, tail, true
		}
	}
	if looksShellCommand(line) {
		return "", line, true
	}
	return line, "", false
}

func looksShellCommand(s string) bool {
	s = strings.TrimSpace(s)
	if s == "" {
		return false
	}
	prefixes := []string{
		"export ", "npm ", "pnpm ", "yarn ", "bun ", "npx ", "pip ", "pipenv ",
		"poetry ", "uv ", "intentproof ", "stripe ",
	}
	for _, p := range prefixes {
		if strings.HasPrefix(s, p) {
			return true
		}
	}
	return strings.Contains(s, " && ")
}
